### ISSUE TITLE
【textinput】append 一个 iconfont 后显示异常

### ISSUE THREAD

**Issue by ganyouyin** [Morning-UI/morning-ui#500]
__问题__

【textinput】append 一个 iconfont 后显示异常

__环境__

- Morning UI版本：0.11.15

__重现步骤__

```html
<v-textinput @value-change="filterRepos" inside-name="检索" append="&#xe674;" class="filter-repo"></v-textinput>
```
```css
.filter-repo {
    float: right;
    width: 250px;
    height: 42px;
    margin-right: 20px;
    .input-group-addon {
        font-family: "iconfont" !important;
        font-style: normal;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
}
```

__实际的结果__

![image](https://user-images.githubusercontent.com/5118959/48404681-c2c4e280-e76b-11e8-9824-d5eecd7e62ce.png)
